name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tests before
      run: cargo test
    - name: Cargo login
      env:
        API_KEY: ${{ secrets.CRATES_IO_KEY }}
      run: |
        cargo login "$API_KEY"
    - name: Publish
      run: cargo publish
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}